name: tests

on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: ["8.4"]
        dependency-version: [prefer-stable]

    name: Tests P${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Pest php coverage tests
        run: php ./vendor/bin/pest --coverage -parallel --min=100

      - name: PHP Stan tests
        run: php ./vendor/bin/phpstan analyse --memory-limit=2G --ansi

      - name: Rector php tests
        run: php ./vendor/bin/rector --dry-run --ansi

      - name: Laravel Pint tests
        run: php ./vendor/bin/pint --test --ansi
